### ISSUE TITLE
Tracking issue: initial addon implementation

### ISSUE THREAD

**Issue by simonihmig** [simonihmig/ember-cli-concat-analyzer#1]
## Architecture

* adds a new `broccoli.middleware` to ember-cli, with its own `broccoli.builder` and `broccoli.watcher`
* uses a custom broccoli plugin (using `broccoli-caching-writer`) to transform the stats output files (`*.json`) of `broccoli-concat` to their corresponding summarized `*.out.json` counterparts, and to dynamically generate the `summary.js` file (similar to what the `broccoli-concat-analyser` CLI does, but using broccoli)
* merges the [static assets](https://github.com/stefanpenner/broccoli-concat-analyser/tree/master/output) from `broccoli-concat-analyser`
* that output is served by the middleware, when the user visits `localhost:4200/_analyze`
* the custom builder/watcher is initialized lazily when the first request hits the middleware  
* when `process.env.CONCAT_STATS` is not set (thus concat stats are not available), the middleware serves an [info page](https://github.com/simonihmig/ember-cli-concat-analyzer/blob/master/lib/output/no-stats/index.html) instead of the stats
* imports processing functions from `broccoli-concat-analyser` (~requires PR https://github.com/stefanpenner/broccoli-concat-analyser/pull/15 to be merged!~)

## Todo

- [ ] fix #2
- [x] enhance [info page](https://github.com/simonihmig/ember-cli-concat-analyzer/blob/master/lib/output/no-stats/index.html) when stats are not enabled
- [ ] support livereload
- [ ] as soon as the `_analyze` URL has been requested, the custom builder/watcher is initialized, and rebuilds the stats output on every following change, causing a performance hit. Can we rebuild only when a new `_analyze` request comes in? 
- [ ] find a way for this addon and `broccoli-concat` to exchange the concat stats using some temporary folder, instead of "polluting" the app folder with the `concat-stats-for` folder
- [ ] smarter caching: use `broccoli-persistent-filter` to only rebuild those `*.out.json` files when their corresponding `*.json` has changed (currently all `*.out.json` are regenerated)
- [ ] add tests
- [ ] add docs

**Comment by simonihmig** [comment]
@stefanpenner here is an initial PoC-style implementation of an ember-cli addon, that makes the stats output of `broccoli-concat-analyser` directly available from `CONCAT_STATS=true ember s`. Kind of works, but certainly needs some more love. 

Would appreciate some early feedback! :) See the code itself as well as the remarks above...

**Comment by simonihmig** [comment]
@stefanpenner had a chance to look at this? Would love some feedback on the general direction, to know if that makes sense so far...
